#!/usr/bin/env python3
"""Does every package the family ships have a Python API page and a mkdocs.yml nav entry?

    tools/release/check_api_pages.py      # report, exit 1 on a finding

The pages themselves (docs/python/<pkg>.md) are no longer committed: the Site workflow generates them
at build time with tools/gen_python_api.py inside the released peclet-cpu container image, so they
describe the released API and cannot go stale (they did at 1.3.0, when they were regenerated by hand).
What a release can still get wrong is COVERAGE, which needs no built modules:

  Every package the family ships has a `PAGES` entry in tools/gen_python_api.py and a mkdocs.yml nav
  entry. The ships list is the metapackage's own: every `peclet-<name>==` pin in the umbrella
  pyproject.toml (base dependencies and extras). `peclet-<name>` documents module `peclet.<name>`,
  except `peclet-core`, the compatibility shell, which has no API of its own (its modules are the
  deprecated re-exports of `peclet.halo` / `peclet.geom`, docs/CORE_BOUNDARY.md) and is covered by
  `peclet.halo`.

The docstrings the pages are generated from are gated separately, on the release candidate's MPI build
trees: tools/release/audit_docstrings.py --strict (check_release_state.sh runs both).

Exit status: 0 clean, 1 on any finding.
"""
from __future__ import annotations

import re
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tools"))
import gen_python_api as gen  # noqa: E402

SHELL_DISTS = {"peclet-core": "peclet.halo"}   # compatibility shell -> the module that carries its API


def shipped_modules() -> dict[str, str]:
    """{distribution: module} for every peclet-<name>== pin of the umbrella metapackage."""
    meta = tomllib.loads((ROOT / "pyproject.toml").read_text())["project"]
    reqs = list(meta.get("dependencies", []))
    for extra in meta.get("optional-dependencies", {}).values():
        reqs += extra
    out = {}
    for r in reqs:
        m = re.match(r"(peclet-[a-z0-9]+)\s*==", r)
        if m:
            d = m.group(1)
            out[d] = SHELL_DISTS.get(d, "peclet." + d[len("peclet-"):])
    return out


def check_coverage() -> list[str]:
    paths = {p for _, _, _, specs in gen.PAGES for p, _ in specs}
    nav = (ROOT / "mkdocs.yml").read_text()
    bad = []
    for dist, mod in sorted(shipped_modules().items()):
        entry = [f for f, _, _, specs in gen.PAGES if any(p == mod for p, _ in specs)]
        if mod not in paths:
            bad.append(f"{dist}: no PAGES entry for {mod} in tools/gen_python_api.py")
        elif not any(f"python/{f}" in nav for f in entry):
            bad.append(f"{dist}: {entry[0]} (page of {mod}) has no mkdocs.yml nav entry")
    return bad


def main() -> int:
    findings = check_coverage()
    for f in findings:
        print(f"  !! {f}")
    if findings:
        return 1
    print("  every shipped package has an API page (tools/gen_python_api.py PAGES) and a nav entry")
    return 0


if __name__ == "__main__":
    sys.exit(main())
